[refactor] Support for openwisp-utils versions 0.6 and 0.7 #77
openwisp/django-loci pull request #78
Opened 2020-11-15 10:19 UTC by devkapilbansal

Updated requirements to support both openwisp-utils versions, i.e. 0.6 and 0.7

Closes #77

2020-11-15 12:04 UTC, pandafy requested changes
@devkapilbansal can break these changes into different commits? One for refactoring and other for upgrading the dependency?

2020-11-15 12:04 UTC, pandafy commented on requirements-test.txt
> +openwisp-utils[qa]>=0.6.0,<=0.7.0
```suggestion
openwisp-utils[qa]>=0.6.0,<0.8
```
This way will support all minor versions of openwisp-utils 0.7

2020-11-15 12:04 UTC, pandafy commented on requirements.txt
> +openwisp-utils>=0.6.0,<=0.7.0
```suggestion
openwisp-utils[qa]>=0.6.0,<0.8
```
This way will support all minor versions of openwisp-utils 0.7

2020-11-16 06:12 UTC, pandafy approved these changes
LGTM :+1: 

Merging deferred to @nemesisdesign

2020-11-17 04:37 UTC, nemesisdesign approved these changes
Thanks @devkapilbansal @pandafy :+1:

2020-11-17 04:38 UTC, merged