[qa] Replace external services with mocks #83
openwisp/django-loci pull request #84
Opened 2021-03-05 14:14 UTC by Purhan

Closes #83

2021-03-05 14:17 UTC, Purhan commented
Although all tests pass after this, some tests still raise exceptions, example:
```
Traceback (most recent call last):
  File "/home/purhan/foss/django-loci/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/purhan/foss/django-loci/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/purhan/foss/django-loci/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/purhan/foss/django-loci/venv/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/purhan/foss/django-loci/venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f28ddb774f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```

2021-03-06 02:09 UTC, nemesisdesign requested changes
@Purhan can you isolate which test is failing? There may be another test in which we need to add mocking.

2021-03-06 02:09 UTC, nemesisdesign commented on requirements-test.txt
> +responses==0.12.1
It's better to use something like `responses~=0.12`

2021-03-06 02:09 UTC, nemesisdesign commented on django_loci/tests/base/static/test-geocode.json
> +}
please add a final blank line, applies to the other file as well

2021-03-06 06:46 UTC, Purhan commented
> @Purhan can you isolate which test is failing? There may be another test in which we need to add mocking.

@nemesisdesign Done, all tests pass without any exceptions now.

2021-03-06 09:52 UTC, devkapilbansal approved these changes
LGTM :+1: 
Tested locally and all test case passed while offline

2021-03-06 17:47 UTC, nemesisdesign approved these changes
Great work, thanks @Purhan @devkapilbansal :+1:

2021-03-06 17:48 UTC, merged