[CI] Moved to github actions #82
openwisp/django-loci pull request #87
Opened 2021-03-14 09:21 UTC by codesankalp

Added github actions for django_loci.

Closes #82

2021-03-14 09:21 UTC, codesankalp commented
Success Build URL: https://github.com/codesankalp/django-loci/actions/runs/651014903

2021-03-15 16:28 UTC, codesankalp commented
@nemesisdesign Can you please review it?

2021-03-15 16:35 UTC, devkapilbansal requested changes

2021-03-15 16:35 UTC, devkapilbansal commented on .github/workflows/ci.yml
> +        sudo apt-get -qq -y install sqlite3 libsqlite3-dev libsqlite3-mod-spatialite gdal-bin
@codesankalp Please break this in multiple lines to increase readability

2021-03-15 16:35 UTC, devkapilbansal commented on .github/workflows/ci.yml
> +        pip install -r requirements-test.txt
Write this in single line only
```suggestion
      run: pip install -r requirements-test.txt
```

2021-03-15 21:21 UTC, devkapilbansal approved these changes
LGTM :+1:

2021-03-15 21:21 UTC, merged

2021-03-15 21:23 UTC, devkapilbansal commented
Rebased the PR to `ci` branch and opened PR #88 to test the build